update libsonic to v0.5.1
basilfx/plugin.audio.subsonic pull request #4
Opened 2016-09-19 21:31 UTC by gordielachance

makes plugin work again on Kodi Krypton (fixes issue
https://github.com/basilfx/plugin.audio.subsonic/issues/3)

2016-09-20 05:30 UTC, basilfx commented on addon.py
> +        self.random_count = int(addon.getSetting("random_count"))
Not sure what will happen if `addon.getSetting("random_count")` returns a non-integer. Maybe wrap it in something like

```python
try:
    self.bitrate = int(addon.getSetting("random_count"))
except ValueError:
    self.bitrate = 0
```

Same applies for other calls below.

2016-09-20 05:30 UTC, basilfx commented on addon.py
> +        for album in self.connection.walk_album_list('newest',size,None,None,None):
PEP8: spaces betweeen arguments.

2016-09-20 05:30 UTC, basilfx commented on addon.py
> +        for album in self.connection.walk_album_list('byGenre',size,None,None,genre):
PEP8: spaces betweeen arguments.

2016-09-20 05:30 UTC, basilfx commented on addon.py
> +        for album in self.connection.walk_album_list('byGenre',size,None,None,genre):
PEP8: spaces betweeen arguments.

2016-09-20 05:31 UTC, basilfx commented on lib/libsonic_extra/__init__.py
> +    def walk_album_list(self, ltype, size=10, fromYear=None,toYear=None, genre=None):
PEP8: spaces betweeen arguments.

2016-09-20 05:32 UTC, basilfx commented on addon.py
> +        for album in self.connection.walk_album_list('newest',size,None,None,None):
I think you can also write `self.connection.walk_album_list('newest', size)`. The `None` arguments are kwargs.

2016-09-20 05:33 UTC, basilfx commented on addon.py
> +        for album in self.connection.walk_album_list('byGenre',size,None,None,genre):
I think you can also write `self.connection.walk_album_list('newest', size, genre=genre)`. The `None` are optional kwargs (they have defaults).

2016-09-20 05:33 UTC, basilfx commented on addon.py
> +        for album in self.connection.walk_album_list('byGenre',size,None,None,genre):
I think you can also write `self.connection.walk_album_list('newest', size, genre=genre)`. The None arguments are optional.

2016-09-20 05:35 UTC, basilfx requested changes
Thanks for this PR. If you address the changes, I am happy to merge them.

2016-09-20 05:35 UTC, basilfx commented on lib/libsonic_extra/__init__.py
> +    def walk_album_list(self, ltype, size=10, fromYear=None,toYear=None, genre=None):
It is not python to have `camelCase` names. use `snake_case`

2016-09-20 14:34 UTC, gordielachance commented
Hi, I made your changes...

I also reorganized the menus and added submenus for albums (Newest / Most played / Rencently played).

The one thing i'm not able to do (that's my first time with Pyton) is to limit the albums query to a 'size' (for pagination).  I don't understand why.
I did create a new option _albums_per_page_, and it seems that it is called correctly, but each time the whole list of albums is fetched; which is quite slow as I have hundreds of albums on Subsonic.
Could you have a look ?

2016-10-04 01:18 UTC, gordielachance commented
Hi, I made a lot of changes in my fork !
Have a look if you have some time... There is now the ability to download and even star tracks :)

2016-10-05 08:04 UTC, gordielachance commented
Hi basilfx,
Sorry to ask, but do you plan to merge my changes ?
I ask because if you prefer rather not, I could rename/split "my" version of the plugin so I could try to make it available on the official Kodi repositories.
Now that I spent so much time working on it (and thanks for your first version which was a great base); I would be glad if i'm not the only one to benefit from it :)
Thanks !

2016-10-05 08:25 UTC, basilfx commented
I don't mind if you fork and work on your own version. That's how GitHub works :-)

After all, I don't use this plugin anymore, so as long as you respect the current [LICENSE](https://github.com/basilfx/plugin.audio.subsonic/blob/master/LICENSE) (don't forget to add yourself!) then I don't mind.

I'll even put deprecated notice in the README and redirect people to your fork.

2017-01-14 14:52 UTC, closed without merging